language: python

python:
  - "3.7"

install:
  - pip install -r requirements/dev.req
  - pip install -r requirements/requirements.req

services:
  - postgresql

script:
  - coverage run -m unittest

after_success:
  - coveralls