sudo: true

language: python

python:
  - "3.7"

install:
  - pip install -r requirements/dev.req
  - pip install -r requirements/requirements.req

services:
  - postgresql
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test' SUPERUSER;" -U postgres
  - wget -c https://repo.mysql.com//mysql-apt-config_0.8.14-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.14-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade

script:
  - coverage run --source . --omit ./setup.py -m unittest

after_success:
  - coveralls