language: python

python:
  - "3.7"

install:
  - pip install -r requirements/dev.req
  - pip install -r requirements/requirements.req

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test' SUPERUSER;" -U postgres

script:
  - coverage run --source . -m unittest

after_success:
  - coveralls